
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ARG BACKGROUND COMMAND OPTION PIPE REDIRECT_APPEND REDIRECT_IN REDIRECT_OUTcommand_list : command\n                    | command_list PIPE commandcommand : COMMAND\n                | COMMAND options\n                | COMMAND options args\n                | COMMAND argsoptions : OPTION\n                | options OPTIONargs : ARG\n            | args ARGredirects : redirect\n                | redirects redirectredirect : REDIRECT_OUT ARG\n                | REDIRECT_IN ARG\n                | REDIRECT_APPEND ARG'
    
_lr_action_items = {'COMMAND':([0,4,],[3,3,]),'$end':([1,2,3,5,6,7,8,9,10,11,12,],[0,-1,-3,-4,-6,-7,-9,-2,-5,-8,-10,]),'PIPE':([1,2,3,5,6,7,8,9,10,11,12,],[4,-1,-3,-4,-6,-7,-9,-2,-5,-8,-10,]),'OPTION':([3,5,7,11,],[7,11,-7,-8,]),'ARG':([3,5,6,7,8,10,11,12,],[8,8,12,-7,-9,12,-8,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command_list':([0,],[1,]),'command':([0,4,],[2,9,]),'options':([3,],[5,]),'args':([3,5,],[6,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command_list","S'",1,None,None,None),
  ('command_list -> command','command_list',1,'p_command_list','parserpy.py',8),
  ('command_list -> command_list PIPE command','command_list',3,'p_command_list','parserpy.py',9),
  ('command -> COMMAND','command',1,'p_command','parserpy.py',16),
  ('command -> COMMAND options','command',2,'p_command','parserpy.py',17),
  ('command -> COMMAND options args','command',3,'p_command','parserpy.py',18),
  ('command -> COMMAND args','command',2,'p_command','parserpy.py',19),
  ('options -> OPTION','options',1,'p_options','parserpy.py',27),
  ('options -> options OPTION','options',2,'p_options','parserpy.py',28),
  ('args -> ARG','args',1,'p_args','parserpy.py',35),
  ('args -> args ARG','args',2,'p_args','parserpy.py',36),
  ('redirects -> redirect','redirects',1,'p_redirects','parserpy.py',43),
  ('redirects -> redirects redirect','redirects',2,'p_redirects','parserpy.py',44),
  ('redirect -> REDIRECT_OUT ARG','redirect',2,'p_redirect','parserpy.py',51),
  ('redirect -> REDIRECT_IN ARG','redirect',2,'p_redirect','parserpy.py',52),
  ('redirect -> REDIRECT_APPEND ARG','redirect',2,'p_redirect','parserpy.py',53),
]
